version: '3'

volumes:
  jenkins_home:

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.511
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      # - ./jenkins_dsl/jenkins-job.groovy:/usr/share/jenkins/ref/init.groovy.d/init.groovy

