pipeline {
    agent any
     tools {
        jdk 'OpenJDK-17'     
        maven 'Maven-3.9.6'   
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Env') {
            steps {
              sh '''
                set -a
                source ../.env
                set +a
                '''
            }
        }
        stage('Print Env') {
          steps {
            echo "JFrog URL: ${env.JFROG_URL}"
          }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    // Archive test result files for download
                    archiveArtifacts artifacts: 'target/surefire-reports/*.xml', fingerprint: true
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
