pipeline {
    agent any
     tools {
        jdk 'OpenJDK-17'     
        maven 'Maven-3.9.6'   
    }

    environment {
        JAVA_HOME = "${tool 'OpenJDK-17'}"
        PATH = "${env.JAVA_HOME}/bin:${tool 'Maven-3.9.6'}/bin:${env.PATH}"
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
