name: Build, Deploy and Generate Reports
on:
  workflow_dispatch:
    inputs:
      pom_version:
        description: 'POM Version'
        required: false
        default: '1.3-SNAPSHOT'
  push:
    branches: [ "Sample-App-Github-Deployer" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: opsera_customer1

    env:
      JFROG_URL: https://trial28qn92.jfrog.io/artifactory
      JFROG_M2_REPO: opsera_customer1_m2
      JFROG_RELEASE_REPO: opsera_customer1_release
      JFROG_TEST_REPORT_REPO: opsera_customer1_test_reports
      POM_VERSION: 1.3-SNAPSHOT

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'


    - name: Build and Deploy (Skip Tests)
      run: |
          mvn -B -DskipTests clean deploy
          echo ${env.JFROG_RELEASE_REPO}
          echo ${env.JFROG_USERNAME}

    - name: Run Tests
      run: mvn test

    - name: Archive JUnit test results
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports/*.xml

    - name: Publish JUnit results to JFrog
      run: |
        TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
        for file in target/surefire-reports/*.xml; do
          curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_TEST_REPORT_PASSWORD }}" \
            -T "$file" \
            "${JFROG_URL}/${JFROG_TEST_REPORT_REPO}/com.mycompany.app.AppTest.${TIMESTAMP}.xml"
        done

    - name: Deliver step
      run: ./jenkins/scripts/deliver.sh
